#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2017 Thierry Ghelew <tlux@ghelew.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

# the first and only parameter is the number of samples (max=3)
NUM_SAMPLE=`expr ${1:-0} : "^[1-3]$" >/dev/null && echo $1 || echo 3`

load="$(sysctl -n vm.loadavg | tr -d '{}')"
cpus="$(sysctl -n hw.ncpu)"

# color if load is too high
echo ${load} | awk -v cpus=$cpus -v ns=$NUM_SAMPLE '
    {
        load_1 = $1; # 1 minute load
        for (i=1 ; i<ns+1;i++)
            output = output  sprintf("%s ",$i);
    }
    END {
        sub(" $", "", output);
        print output; #full text
        print output; #short text
        if (cpus <= load_1) {
            print "#FF0000";
            exit 33;
        }
    }
'
